version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: alsadek_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alsadek_spices
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alsadek_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: alsadek_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alsadek.qa
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - alsadek_network

volumes:
  postgres_data:

networks:
  alsadek_network:
    driver: bridge